### PR TITLE
Rename old_grids to grid

### PR DESCRIPTION
**Pull request by FarnazH**

### CODE REVIEW

**Comment by matt-chan** [comment]
Hmm? I thought we merged this in already?

**Comment by FarnazH** [comment]
The only `pylint` error left is `no-name-in-module` which I believe can be ignored. So, this should be good to go.

**Comment by FarnazH** [comment]
> Hmm? I thought we merged this in already?

No. I closed that PR because it was failing on Travis. It is properly done now.

**Comment by FarnazH** [comment]
No, those changes were already merged in an earlier PR. So, we are good to go I think.

**Comment by matt-chan** [comment]
Ah okay. Then I'll merge it.

**Pull request merged**
