### PR TITLE
[added] alvarez covalent radii

### PR DESCRIPTION
**Pull request by marco-2023**
Added the covalent radii database from:
    B. Cordero,.V. Gómez, A. E. Platero-Prats, M. Revés,J. Echeverría,
    E. Cremades, F Barragána, S. Alvarez, Dalton Trans., 2008, 2832-2838
    https://doi.org/10.1039/B801115J

Observations:
    - The C covalent radius value was taken as reported for Csp3
    - For Mn (Z=25), Fe (Z=26), and Co (Z=27) the covalent radii values were
      taken as reported for the low spin electronic configuration.
    - These covalent radii values can be accessed using get_cov_radii(atnums, type="alvarez")

    modified:   src/grid/utils.py

### CODE REVIEW

**Comment by Ali-Tehrani** [comment]
Thank you for this pull request. I added a test and fixed some issues.

**Comment by FarnazH** [comment]
@Ali-Tehrani, I noticed your commit message that "Based on my previous results they didn't match my results up to 4 decimal places, probably based on the conversion factor from angstrom to bohr." 
Can you please share how you got your numbers? If you have a code snippet, please share.

**Comment by FarnazH** [comment]
Thanks, @Ali-Tehrani. Your conversion factor is the same as `iodata`, see:

```python
>>> from iodata.utils import angstrom
>>> angstrom
1.8897261246257702
>>> angstrom - 1.8897261339213
-9.295529901365285e-09
```

@marco-2023, what conversion factor were you using? I just want to make sure that was the reason your numbers were different from Ali's.

**Comment by marco-2023** [comment]
@FarnazH  I revised the numbers. The numbers were different because I used `1.88973` as the conversion constant (not the one in `iodata`). I also made a mistake parsing the results in order to add the underscores. Sorry for that. It won't happen again.

**Comment by FarnazH** [comment]
No worries @marco-2023. I just wanted to make sure we understand what was happening. We all make mistakes, and that's why we have code reviews :-) Thanks for your contribution.

**Pull request merged**
