### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by Ali-Tehrani**
Related to #231. This removes the defected logo from the website and adds the new logo to the table of contents, it looks like this:
Screenshot from 2024-01-31 19-44-13

The other option is to have the grid in the table of contents above the image, but I don't like it

Screenshot from 2024-01-31 19-40-37

### CODE REVIEW

**Comment by marco-2023** [comment]
Hi @Ali-Tehrani
Can we use a .svg (vectorial) graphic instead of the .png? This would prevent the image from pixelating when zoomed.

**Comment by FarnazH** [comment]
@Ali-Tehrani I am fine with both suggestions you had, but I agree that not having the grid above the image looks nicer.

**Review by FarnazH — COMMENTED** [review]
@Ali-Tehrani I am fine with both suggestions you had, but I agree that not having the grid above the image looks nicer.

**Comment by Ali-Tehrani** [comment]
I've tried doing it with svg but I'll have to convert it to png anyways to make the background transparent and to invert.  I've zoomed in on the images myself (when on the website) and don't see any problems with it.  I've added a *.svg file for it in the images in case anyone else wants to do it

**Comment by marco-2023** [comment]
Hi @Ali-Tehrani, I can make the .svg with transparent background and using vectorial graphics. Can you send me the file used to create the logo? So I can use the same fonts? Thank you  very much.

**Comment by Ali-Tehrani** [comment]
Hi @marco-2023,  I've attached the powerpoint that I used. The font is Franklin Gothic
[grid_graphical_abstract(1).pptx](https://github.com/theochem/grid/files/14140749/grid_graphical_abstract.1.pptx)

**Comment by marco-2023** [comment]
grid_logo_vect_white


@Ali-Tehrani Here is the vectorial white grid logo without background. It took me some time to reproduce it. Please tell me what you think. If you need any other colours or modifications let me know

**Comment by Ali-Tehrani** [comment]
Was the filled "D" letter intended? Other than that, I really like!

**Comment by PaulWAyers** [comment]
I think it looks good. I keep wondering if the "d" should be a $\nabla$ or a $\tfrac{d}{dx}$ but this isn't important.

**Comment by marco-2023** [comment]
> Was the filled "D" letter intended? Other than that, I really like!
@Ali-Tehrani can you point out which D letter is filled so I can fix it? Any difference with the png logo is unintended.

**Comment by Ali-Tehrani** [comment]
Screenshot from 2024-02-02 13-21-34

For me it looks like the above, where the D letter is filled in

**Comment by marco-2023** [comment]
@Ali-Tehrani I think it should be a "selection" problem. This is how I see it using github dark theme
image

Below I add the same vectorial graph using the original colour. 

grid_logo_vect_orig_colour

**Comment by marco-2023** [comment]
Below is the logo following @PaulWAyers idea of using $\nabla$. For using the derivative (I don't have it clear)
grid_logo_vect_paul_orig_color

grid_logo_vect_paul_white

**Review by marco-2023 — APPROVED** [review]
I added vectorial images for the logos, and changed the logo used on website to vectorial.

I will be merging it.

**Comment by marco-2023** [comment]
Some of the tests and workflows were failing because of inconsistent treatment of variables across python versions. Fixed that. Merging the PR

**Pull request merged**
