### PR TITLE
Refactor Angular Grid

### PR DESCRIPTION
**Pull request by FarnazH**
The commit messages should be self-explanatory. I talked about 5e4323095b91017f516aff346c023dfb17e7ad21 with @marco-2023 and @PaulWAyers yesterday, and they also agreed that we need an argument that supports more than just two angular grid methods. Feel free to let me know what you think.

### CODE REVIEW

**Comment by marco-2023** [comment]
It looks good to me.

**Comment by FarnazH** [comment]
@marco-2023, I just noticed that I didn't make the corresponding changes to the notebooks. Can you please take care of it? I am working on other parts of the code, so I would appreciate your help. Thanks.

**Comment by marco-2023** [comment]
@FarnazH No problem, I am on it. Should I change the code snippets in the paper too?

**Comment by FarnazH** [comment]
> @FarnazH No problem, I am on it. Should I change the code snippets in the paper too?

That would be appreciated. Thanks @marco-2023.

**Review by marco-2023 — APPROVED** [review]
Looks good to me

**Comment by PaulWAyers** [comment]
Cf. #237 for a reason why the new nomenclature is better.

**Pull request merged**
