### PR TITLE
Minor Updates

### PR DESCRIPTION
**Pull request by FarnazH**
Fix multiple things as described in the commit messages.

### CODE REVIEW

**Comment by FarnazH** [comment]
@matt-chan After merge, I think we should tag this to make a new release independent of `gbaiss` and `iodata` under the name `theochem/grid`. Can you please do that?

**Comment by matt-chan** [comment]
> a new release independent of gbaiss and iodata under the name theochem/grid

@FarnazH Do you mean in conda?

**Comment by FarnazH** [comment]
> > a new release independent of gbaiss and iodata under the name theochem/grid
> 
> @FarnazH Do you mean in conda?

@matt-chan yes, a conda release.

**Comment by PaulWAyers** [comment]
Doing nuclear-nuclear repulsion energy in C is sort of absurd. If that is *ever* within a factor of 1000 of the time-limiting step in your calculation it is only because your calculation crashed before it could compute anything else. This is one of the type of obvious thing that should be taken care of when refactoring...it doesn't even require testing to make sure that it is a computational bottleneck.

**Pull request merged**
