### PR TITLE
Cubic Grid Tutorial for Iso-Surface Visualization

### PR DESCRIPTION
**Pull request by FarnazH**
This is from Quickstart.ipynb notebook from https://github.com/theochem/grid/pull/202. See: [908178c](https://github.com/theochem/grid/pull/202/commits/908178ceb33e238242fa19c654a19924fa057509)

### CODE REVIEW

**Comment by Ali-Tehrani** [comment]
I really like these examples.  Unless anyone says otherwise, I am going to merge this notebook with the already cubic_grid notebook. The first example of visualization can fall under the Tensor1DGrid. Then the second example of dual descriptor can fall under the Uniform Grid Section

**Comment by FarnazH** [comment]
Thanks @Ali-Tehrani. Let me know when you are done, and I will do one last review of the notebook.

**Comment by Ali-Tehrani** [comment]
Okay, it is ready to be reviewed. I merged the two notebooks while fixing up the section/typos/wording, and removed the original notebook.

**Review by Ali-Tehrani — APPROVED** [review]

**Comment by Ali-Tehrani** [comment]
I'm going ahead and merging this notebook.

**Pull request merged**
