### PR TITLE
Add example of local(atomic) property integation

### PR DESCRIPTION
**Pull request by marco-2023**
Added an example showing how to extract a local or atomic grid from a molecular grid and integrate the local property.

I went through the MolGrid class and at the end it has an elegant way to get the indices of each atomic grid. Because of this, I think it is not necessary to make modifications to the methods. I made this new PR where the example outcome is achieved without tampering with the class. This should substitute PR #209

### CODE REVIEW

**Review by FarnazH — APPROVED** [review]
Thanks @marco-2023. I pushed some changes, but nothing substantial. I will merge this PR. If you decide to add a formula, please make another PR.

**Comment by marco-2023** [comment]
@FarnazH  I am trying to use the new  `gbasis from_iodata API` and I am not able to make it work, it gives me an error even for this notebook see image:
image

I already tried using the most updated master branches of both iodata and gbasis. Is the API change implemented in another non-yet-merged branch?

**Comment by FarnazH** [comment]
@marco-2023, please use this branch https://github.com/theochem/gbasis/pull/140
This PR will be merged next week. Sorry for the inconvenience.

**Comment by marco-2023** [comment]
Thank you very much!

**Pull request merged**
